apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: site-quality-gate
  namespace: site-quality-gate
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: site-quality-gate
  template:
    metadata:
      labels:
        app: site-quality-gate
    spec:
      containers:
        - name: web
          image: site-quality-gate:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "APP_VERSION_VALUE"
            - name: INJECT_ERRORS
              value: "INJECT_ERRORS_VALUE"
            - name: INJECT_LATENCY_MS
              value: "INJECT_LATENCY_MS_VALUE"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  strategy:
    canary:
      canaryService: site-quality-gate-canary
      stableService: site-quality-gate-stable
      trafficRouting:
        nginx:
          stableIngress: site-quality-gate
          # Sem canary-by-header-value: "always" forca o canary e "never" forca o stable.
          additionalIngressAnnotations:
            canary-by-header: X-Canary
      steps:
        - setWeight: 10
        - analysis:
            templates:
              - templateName: canary-vs-stable
        - pause:
            duration: 10m
        - setWeight: 50
        - analysis:
            templates:
              - templateName: canary-vs-stable
        - pause:
            duration: 10m
