apiVersion: v1
kind: Service
metadata:
  name: site-quality-gate-canary
  namespace: site-quality-gate
spec:
  selector:
    app: site-quality-gate
  ports:
    - name: http
      port: 80
      targetPort: 8080
